export const type = {
    ROOM_CHECK: {
        RESPONSE_FAILURE: "CHECK_ROOM_RESPONSE_FAILURE",
        RESPONSE_SUCCESS: "CHECK_ROOM_RESPONSE_SUCCESS", 
    },
    ROOM_DESTROY: {
        RESPONSE_FAILURE: "DESTROY_ROOM_RESPONSE_FAILURE",
        RESPONSE_SUCCESS: "DESTORY_ROOM_RESPONSE_SUCCESS", 
    }
}